export const plans = [
  {
    id: 0,
    name: "Pro",
    price: "$59",
    description: "Ideal for professionals and small teams.",
    features: [
      "Unlimited AI image generations",
      "High-quality image outputs",
      "Priority chat support",
      "API access for 30 projects",
      "Access to premium AI models",
      "Faster processing speeds",
      "Cloud storage for generated images",
      "Early access to new features",
    ],
  },
  {
    id: 1,
    name: "Pre Release Plan",
    price: "Free",
    description: "Perfect for individuals getting started with AI.",
    features: [
      "5 AI image generations daily",
      "Basic text-to-image quality",
      "Chat support",
      "API access for limited projects",
      "Watermarked AI-generated images",
      "Access to community forums",
      "Limited AI model selection",
    ],
    popular: true,
  },
  {
    id: 2,
    name: "Enterprise",
    price: "$99",
    description: "Advanced features for growing businesses.",
    features: [
      "Everything in Pro plan",
      "Ultra HD image quality",
      "Dedicated account manager",
      "Custom AI model training",
      "API access for unlimited projects",
      "24/7 premium customer support",
      "Team collaboration tools",
      "White-label solutions",
      "Enhanced data privacy and security",
    ],
  },
];
